### PR TITLE
JBERET-561 Change visibility of scopes implementations

### PR DESCRIPTION
**Pull request by liweinan**

### CODE REVIEW

**Comment by liweinan** [comment]
patch from: https://github.com/jberet/jsr352/pull/232

**Comment by liweinan** [comment]
The CI passed and I need to do tck testing for this.

After all the testings are done on the main branch I'll backport it to the branch https://github.com/jberet/jsr352/tree/2.1

**Comment by luca-bassoricci** [comment]
Latest build passed using liweinan:patching_232 as source

**Comment by liweinan** [comment]
The standalone TCK test passed: 

image

The next step I need to run the deployment TCK tests in WildFly.

I'm currently using these projects to do the tests manually:

- https://github.com/jberet/jberet-tck-porting
- https://github.com/liweinan/jakarta.batch.official.tck-2.1.1

In the future I need to make automate the process.

@luca-bassoricci Today it's too late for me. I'll go on working on this during the weekend and after the work is done I'll do the release.

**Comment by liweinan** [comment]
relative PR: https://github.com/quarkiverse/quarkus-jberet/pull/123

**Comment by liweinan** [comment]
I have used the newly added `test-deployment` to generate the provisioned WildFly server:

- https://github.com/jberet/jsr352/tree/main/test-deployment

And followed the steps here to do the TCK testing:

- https://github.com/jberet/jsr352/pull/381#issuecomment-1764776583

And the TCK tests passed:

image

I'll merge this PR and do the release soon.

**Pull request merged**
