### PR TITLE
Support additional Serialization mechanisms

### LINKED ISSUE #134: Support additional Serialization mechanisms
For SVM native image, Java Serialization is not supported yet.

We can workaround this, by use SVM Substitute with a supported Serialization mechanism (Jsonb for instance).

Unfortunately, this still raises an issue of different behaviours between the JVM and SVM executions, plus if using a persistent repository the data serialization is incompatible.

Ideally, we could support different Serialization mechanisms in JBeret and pick which one to use with a configuration. You won't be able to change Serialization after the first execution with a persistent store, but at least it would allow you to keep consistency between the JVM and SVM.

### PR DESCRIPTION
**Pull request by radcortez**
Fixes #134

### CODE REVIEW

**Comment by radcortez** [comment]
ping @chengfang

**Comment by radcortez** [comment]
Thanks @chengfang.  Please, let me know when can we have a release.

**Comment by chengfang** [comment]
1.4.1.Final released on 2021-03-29.

**Comment by radcortez** [comment]
Great! Thanks!

**Pull request merged**
