### PR TITLE
JBERET-561 Change visibility of scopes implementations

### PR DESCRIPTION
**Pull request by chengfang**
https://issues.redhat.com/browse/JBERET-561

Required by https://github.com/quarkiverse/quarkus-jberet/pull/123

### CODE REVIEW

**Comment by luca-bassoricci** [comment]
https://github.com/quarkiverse/quarkus-jberet/pull/123#issuecomment-1147165635

**Comment by luca-bassoricci** [comment]
https://github.com/quarkiverse/quarkus-jberet/pull/123#issuecomment-1406124604

**Comment by liweinan** [comment]
@chengfang Can I merge this PR now? In addition, can I port this into the main branch?

**Comment by luca-bassoricci** [comment]
@liweinan let me update my PR with latest Quarkus and JBeret code.
I'll ping you when I am done.

**Comment by luca-bassoricci** [comment]
@liweinan 
https://github.com/quarkiverse/quarkus-jberet/pull/123#issuecomment-1844973833
I also aligned code to latest jberet codebase but this PR is still bounded to pre-jakarta.
I'm waiting for @radcortez's response because I would like to avoid you to merge an incomplete PR.

**Comment by liweinan** [comment]
@luca-bassoricci Thanks for the update! In addition do you want to add more commits into this PR?

**Comment by luca-bassoricci** [comment]
I haven't additional modification.
From my POV what has been done since now should be enough.

**Comment by liweinan** [comment]
https://github.com/quarkiverse/quarkus-jberet/pull/123

**Comment by liweinan** [comment]
@luca-bassoricci I'll be on PTO next week(and it will be two weeks holidays), if we can finish this by this weekend that would be great :D

**Comment by liweinan** [comment]
btw I start to do the TCK testing for this PR. @chengfang

**Comment by luca-bassoricci** [comment]
> @luca-bassoricci I'll be on PTO next week(and it will be two weeks holidays), if we can finish this by this weekend that would be great :D

On I have already prepared a pipeline (https://github.com/quarkiverse/quarkus-jberet/pull/123/commits/a38ed7bc72b5ed8124daa200ec7dba924feeb467) to build the current main on my side and use the generated artifacts as dependency; I suppose I can use this PR branch but code need to be aligned to JBeret 2.x codebase before.

**Comment by luca-bassoricci** [comment]
On my side I'm ready: you have to align this PR to jberet 2.x because on quakus-jberet extension we dropped support for Quarkus 2.x in favor of Quarkus 3 (which use jakarta namespace).
If you don't want to merge I can use chengfang:scope-impl-public-JBERET-561 on my side to make a build and see if all is working fine; I just write https://github.com/quarkiverse/quarkus-jberet/pull/123#issuecomment-1855665287 to @radcortez for an advice because I have no experience about PR using external project as depencency.

let me know! 👍

**Comment by liweinan** [comment]
@luca-bassoricci okay I'll work on my side once I finish testing I'll merge this and do the patching for other branches.

**Comment by liweinan** [comment]
I have added CI test to the branch and I need to do the TCK testing for this PR. Today is too late for me, I'll try to finish working on this by this week(and also on branch 2.x together with the main branch). If I can't complete this by this weekend I'll finish working on this next week.

**Comment by liweinan** [comment]
@luca-bassoricci If you don't need the patch on this branch anymore, I'll close it.

**Comment by luca-bassoricci** [comment]
> @luca-bassoricci If you don't need the patch on this branch anymore, I'll close it.

Feel free to close it!

**Pull request closed without merging**
