### PR TITLE
Script public constructor and getters.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Review by chengfang — APPROVED** [review]

**Comment by radcortez** [comment]
@chengfang any idea when we will have a release for this? Thanks!

**Comment by radcortez** [comment]
And would be interesting to include some other stuff :)

**Comment by chengfang** [comment]
@radcortez what else you need?

**Comment by radcortez** [comment]
This one as well: https://github.com/jberet/jsr352/pull/137

**Pull request merged**
