### PR TITLE
JBERET-138 Make JdbcItemWriter work with local transaction.

### PR DESCRIPTION
**Pull request by lbtc-xxx**

### CODE REVIEW

**Comment by jamezp** [comment]
I'm not sure we want to do this. The writer should open and close any connections in the `ItemWriter.writeItems(List<Object> items)` method. The reader should just use a non-transactional data source. Using a local transaction like this wouldn't allow a container managed transaction to be used.

**Comment by lbtc-xxx** [comment]
Thanks for the feedback. do you mean I should use javax.transaction.UserTransaction instead of java.sql.Connection when running it on the application server?

**Comment by lbtc-xxx** [comment]
OK I think now I got it. we only need to care java.sql.Connection which acquired by DriverManaget.getConnection() on SE environment. please correct me if I am still wrong.

**Comment by jamezp** [comment]
In EE transactions are managed by the container. When you use a container managed transactional `DataSource` and issue a `DataSource.getConnection()` that connection gets enlisted in the transaction. The connection should be closed and then the commit should happen on the transaction.

The issue is there is a transaction on the `ItemReader.open`. If you do a `DataSource.getConnection()` and cache the connection to be used in the `ItemReader.readItem()` method you've broken a transactional boundary. This doesn't happen if you use a non-JTA `DataSource` because the connection would not be enlisted in the transaction.

In SE everything is a local transaction so it doesn't matter. Unless of course you're using JCA in SE.

**Comment by lbtc-xxx** [comment]
Thank you for the detailed explanation. now everything is clear :)

**Pull request closed without merging**
