### PR TITLE
[JBERET-140] Only update the start and end times when the appropriate status is set for the JobExecution

### PR DESCRIPTION
**Pull request by jamezp**
The start time should only be set once the batch state is `STARTED`. The end time should only be set once the state is `COMPLETED`, `STOPPED` or `FAILED`.

Note that a couple `PurgeJdbcRepositoryIT` tests failed for me, but they also failed on master. I don't think it has to do with this commit.

### CODE REVIEW

**Comment by jamezp** [comment]
I did not run a TCK test either. I'll see if I can figure out how to do that.

**Comment by chengfang** [comment]
There are a couple of NPE when calling getEndTime(), and maybe getStartTime(), now that they can return null values.
around JobRepository line 586, and other places.

**Comment by jamezp** [comment]
Looks like I didn't miss one `getEndTime()` in the `JdbcRepository`.  Where are the others? The ones for the step should be safe as the start time is set in the constructor. I didn't see a contract on the `StepExecution` to indicate when the start time needed to be set.

**Comment by chengfang** [comment]
There were quite a few test failures but could be from the same place you identified.  Can you check in the fix?

**Comment by jamezp** [comment]
Test as in unit or TCK? Unit tests passed for me yesterday.

**Comment by chengfang** [comment]
TCK tests.

**Pull request merged**
