### PR TITLE
[JBERET-165] Only close item readers and writers once.

### PR DESCRIPTION
**Pull request by jamezp**

### CODE REVIEW

**Comment by chengfang** [comment]
During a retry, the reader and writer are closed and re-opened (in rollbackCheckpoint method, around line 635).  As part of the close operation, we set the flag to closed=true, but didn't update the flag after the reader/writer is re-opened.  So next time when they need to be closed, it will just skip since the flag is still closed=true.

**Comment by jamezp** [comment]
Yup. In fact any time we open should should reset the flag. Thanks for pointing that out. I'll get it fixed.

**Comment by jamezp** [comment]
@chengfang WDYT of the changes?

**Comment by chengfang** [comment]
looks good.

**Pull request merged**
