### PR TITLE
JBERET-548 fixed Automatic-Module-Name in MANIFEST.MF

### PR DESCRIPTION
**Pull request by Zerrossetto**
https://issues.redhat.com/browse/JBERET-548

### CODE REVIEW

**Comment by chengfang** [comment]
I'd like to avoid having to modify the pom for each submodule. There are a few other submodules besides jberet-core, jberet-se, like jberet-support, jberet-rest, etc.  If these submodules all inherit the same property (automatic.module.name), it will be resolved dynamically for each submodule to produce a valid module name.

Now we just need to fix the value of this property. It currently is `${project.groupId}.${project.artifactId}`. My thinking is, we can just use `project.artifactId` (jberet-core, jberet-se) replacing `-` with `.`.  So we will have module names like jberet.core, jberet.se, jberet.support, etc.

To do that, we can add the following plugin to `<plugin-mangement>` section, and use it in `<plugins>` section:
```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${maven.build-helper.version}</version>
                <executions>
                    <execution>
                        <id>xxx</id>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>automatic.module.name</name>
                            <value>${project.artifactId}</value>
                            <regex>\-</regex>
                            <replacement>\.</replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Zerrossetto** [comment]
Yes, it makes sense, but I tried to stick to what was agreed in Jira. I didn't want to change too much the module name structure by removing the starting "org."
Another approach, maybe a bit too overengineered, would be to capture the repetitions of words in the module name that are followed by a dash. So it would become something like this:

`
<plugin>
   <groupId>org.codehaus.mojo</groupId>
   <artifactId>build-helper-maven-plugin</artifactId>
   <executions>
      <execution>
         <id>add-regex-properties</id>
         <goals>
            <goal>regex-properties</goal>
         </goals>
         <configuration>
            <regexPropertySettings>
               <regexPropertySetting>
                  <name>automatic.module.name</name>
                  <value>${project.groupId}.${project.artifactId}</value>
                  <regex>([a-z]+)\.\1-</regex>
                  <replacement>$1\.</replacement>
                  <failIfNoMatch>false</failIfNoMatch>
               </regexPropertySetting>
            </regexPropertySettings>
         </configuration>
      </execution>
   </executions>
</plugin>
` 
this creates both org.jberet.core and org.jberet.se. Any possible future module (i.e. jberet-support) would follow the same path, as long as the current naming convention is followed.

**Comment by chengfang** [comment]
That's a great idea. Can you make sure various forms of artifacts can be properly transformed?  We have artifactIds like `jberet-rest-common` with multiple dashes, `jberet-rest-api`, `wildfly-jberet-samples`

**Comment by Zerrossetto** [comment]
matching `([a-z]+)\.\1-|-` and replacing it with `$1.` covers all the cases you have shown.
See it by yourself.
[https://regex101.com/r/iyHd4G/1](https://regex101.com/r/iyHd4G/1)

If it's fine as a solution I'll push it.

**Review by chengfang — APPROVED** [review]

**Pull request merged**
